export const SET_PLACES = "SET_PLACES";

export const SET_POLLUTION_DETAILS = "SET_POLLUTION_DETAILS";

export const SET_TRANSPORT_MODE = "SET_TRANSPORT_MODE";

export const TRY_AUTH = 'TRY_AUTH';

export const UI_PAID_VERSION = 'UI_PAID_VERSION';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";